name: protube_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  youtube_player_flutter: ^9.0.0
  youtube_explode_dart: ^2.0.0
  shared_preferences: ^2.2.3 
  http: ^1.2.0
  # 🌟 एकदम स्टेबल शेयर पैकेज (इसे API 34 नहीं चाहिए) 🌟
  share_plus: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
