name: protube_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: any
  shared_preferences: any
  youtube_player_flutter: any
  # 🌟 ये रहे हमारे नए बैकग्राउंड म्यूजिक वाले पैकेजेस 🌟
  youtube_explode_dart: ^2.5.3
  just_audio: ^0.9.36
  audio_session: ^0.1.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
