name: protube_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  youtube_player_flutter: ^9.0.0
  youtube_explode_dart: ^2.0.0
  shared_preferences: ^2.2.3 
  http: ^1.2.0
  share_plus: ^7.2.2
  
  # 🌟 स्मार्ट और मॉडर्न पैकेजेस (कोई पुरानी एरर नहीं देंगे) 🌟
  perfect_volume_control: ^2.1.2
  screen_brightness: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
