name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create Flutter Project
        run: flutter create --project-name protube_app .

      - name: Get Dependencies
        run: flutter pub get

      # 🌟 THE SOLID CURE: यह कोड एंड्रॉइड की सारी सख्तियों को बायपास कर देगा 🌟
      - name: The Solid Cure (Fix Old Package Errors)
        run: |
          GRADLE_FILE=$(ls /home/runner/.pub-cache/hosted/pub.dev/flutter_inappwebview-*/android/build.gradle | head -n 1)
          sed -i 's/proguard-android.txt/proguard-android-optimize.txt/g' $GRADLE_FILE
          sed -i 's/android {/android {\n    namespace "com.pichillilorenzo.flutter_inappwebview"/g' $GRADLE_FILE

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
